// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efevsodqbptyduwokjyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmZXZzb2RxYnB0eWR1d29ranlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExOTE2MDksImV4cCI6MjA2Njc2NzYwOX0.6_It1w1TIeVJ6ZsIaqHWHYV53ZOnTG2smT9_Dtf8PmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});